# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  coverage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Calc coverage 
      run: export PATH=$PATH:$(go env GOPATH)/bin   
    - name: Test & publish code coverage
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
         go get -u github.com/jandelgado/gcov2lcov
         go test -coverprofile=coverage.out && gcov2lcov -inputfile=coverage.out -outfile=coverage.lcov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}    

    # Runs a set of commands using the runners shell.
